"""Tests for the compression-expansion ramp addition to underPINN:

* ``underPINN.pde.compressible_euler.CompressibleEulerPDE
  .prandtl_meyer_expansion`` -- the Prandtl-Meyer exact-expansion-fan
  relation (new; ``oblique_shock`` already existed and is covered
  elsewhere by ``TestCompressibleEulerReturnType`` in
  ``test_pde_signatures.py``).
* ``underPINN.geometry.ramp.CompressionExpansionRampGeometry`` -- the new
  two-corner (compression + expansion) wall geometry, alongside the
  existing single-corner ``RampGeometry``.

Verified against the same textbook values and physical sanity checks used
when this feature was built (see ``benchmarks/rebuttal/ablations
/ablate_qr_deim_ramp_ce.py``'s module docstring for the full narrative):
standard Prandtl-Meyer function values, and the fact that an oblique shock
followed by an isentropic expansion back to the original flow angle lands
close to but not exactly at the original freestream state -- the expected
signature of entropy generated by the (irreversible) shock, which the
(isentropic) expansion cannot undo.
"""
from __future__ import annotations

import math

import numpy as np
import pytest

from underPINN.pde.compressible_euler import CompressibleEulerPDE
from underPINN.geometry.ramp import CompressionExpansionRampGeometry


# ---------------------------------------------------------------------------
# Prandtl-Meyer function and expansion-fan relation
# ---------------------------------------------------------------------------

class TestPrandtlMeyerFunction:
    """nu(M), gamma=1.4 -- standard textbook values (e.g. Anderson,
    *Fundamentals of Aerodynamics*, Table A.5)."""

    def test_nu_at_M1_is_zero(self):
        assert CompressibleEulerPDE._pm_nu(1.0, 1.4) == pytest.approx(0.0, abs=1e-9)

    def test_nu_matches_textbook_values(self):
        gamma = 1.4
        # (M, expected nu in degrees)
        cases = [(1.5, 11.91), (2.0, 26.38), (3.0, 49.76)]
        for M, expected_deg in cases:
            nu_deg = math.degrees(CompressibleEulerPDE._pm_nu(M, gamma))
            assert nu_deg == pytest.approx(expected_deg, abs=0.02)

    def test_nu_max_as_M_to_infinity(self):
        gamma = 1.4
        nu_deg = math.degrees(CompressibleEulerPDE._pm_nu(1e6, gamma))
        nu_max_expected = 90.0 * (math.sqrt((gamma + 1.0) / (gamma - 1.0)) - 1.0)
        assert nu_deg == pytest.approx(nu_max_expected, abs=0.05)
        assert nu_deg == pytest.approx(130.45, abs=0.05)

    def test_nu_monotonic_increasing(self):
        gamma = 1.4
        machs = [1.0, 1.2, 1.5, 2.0, 2.5, 3.0, 4.0, 6.0]
        nus = [CompressibleEulerPDE._pm_nu(M, gamma) for M in machs]
        assert all(b > a for a, b in zip(nus, nus[1:]))

    def test_mach_from_nu_inverts_nu(self):
        gamma = 1.4
        for M in (1.3, 2.0, 2.5, 3.5):
            nu = CompressibleEulerPDE._pm_nu(M, gamma)
            M_back = CompressibleEulerPDE._pm_mach_from_nu(nu, gamma)
            assert M_back == pytest.approx(M, rel=1e-4)


class TestPrandtlMeyerExpansion:
    def setup_method(self):
        self.pde = CompressibleEulerPDE(model=None, gamma=1.4)

    def test_known_expansion_example(self):
        """M1=2.0, deflect 10 deg: M2 ~ 2.385 (a standard worked example;
        the pressure ratio is derived here from the same isentropic
        formula used internally, cross-checked independently against the
        well-known isentropic table value p/p0(M=2.0)=0.1278)."""
        result = self.pde.prandtl_meyer_expansion(
            M1=2.0, rho1=1.0, u1=1.0, v1=0.0, p1=1.0, delta_deg=10.0)
        assert result["M2"] == pytest.approx(2.385, abs=0.01)

        def p_over_p0(M, gamma=1.4):
            return (1.0 + 0.5 * (gamma - 1.0) * M * M) ** (-gamma / (gamma - 1.0))
        assert p_over_p0(2.0) == pytest.approx(0.1278, abs=1e-4)

    def test_mach_increases_pressure_density_decrease(self):
        """Physical sanity: expanding flow accelerates and depressurises."""
        r = self.pde.prandtl_meyer_expansion(
            M1=2.5, rho1=1.65, u1=2.75, v1=0.48, p1=1.47, delta_deg=10.0)
        assert r["M2"] > 2.5
        assert r["p2"] < 1.47
        assert r["rho2"] < 1.65

    def test_shock_then_expansion_round_trip_near_freestream(self):
        """The specific check this feature's correctness rested on: a
        weak oblique shock (M=3, ramp angle 10 deg) followed by an
        isentropic expansion back to the original flow angle lands close
        to, but measurably above, the original freestream pressure -- the
        entropy the shock generated cannot be undone by an isentropic
        process. Too close (no gap) or too far (badly wrong) would both
        indicate a bug."""
        M_inf, theta = 3.0, 10.0
        rho1, u1, v1, p1 = self.pde.freestream(M_inf)

        shock = self.pde.oblique_shock(M_inf, theta)
        exp_ = self.pde.prandtl_meyer_expansion(
            shock["M2"], shock["rho2"], shock["u2"], shock["v2"], shock["p2"],
            delta_deg=theta)

        assert exp_["M2"] == pytest.approx(M_inf, abs=0.1)
        assert exp_["p2"] == pytest.approx(p1, rel=0.02)
        # But not exact -- entropy was generated by the shock.
        assert exp_["p2"] != pytest.approx(p1, rel=1e-6)
        assert exp_["p2"] > p1   # post-shock-then-expansion state is at
                                # very slightly higher pressure than the
                                # untouched freestream on this branch, per
                                # the actual computed round-trip.
        # Flow direction returns exactly to horizontal (deflected +theta
        # by the shock, then -theta by the expansion).
        angle_deg = math.degrees(math.atan2(exp_["v2"], exp_["u2"]))
        assert angle_deg == pytest.approx(0.0, abs=1e-3)


# ---------------------------------------------------------------------------
# CompressionExpansionRampGeometry
# ---------------------------------------------------------------------------

class TestCompressionExpansionRampGeometry:
    def setup_method(self):
        self.geom = CompressionExpansionRampGeometry(
            theta1_deg=10.0, theta2_deg=0.0, x1=0.4, x2=1.0, L=1.6, H=0.8)

    def test_wall_continuous_at_corners(self):
        """y_wall(x) must not jump at either corner -- both segments meet
        exactly, since a discontinuous wall would be an unphysical
        geometry (a gap or overlap in the solid boundary)."""
        eps = 1e-5
        y_left = self.geom.y_wall(np.array([self.geom.x1 - eps]))[0]
        y_right = self.geom.y_wall(np.array([self.geom.x1 + eps]))[0]
        assert y_left == pytest.approx(y_right, abs=1e-4)

        y_left2 = self.geom.y_wall(np.array([self.geom.x2 - eps]))[0]
        y_right2 = self.geom.y_wall(np.array([self.geom.x2 + eps]))[0]
        assert y_left2 == pytest.approx(y_right2, abs=1e-4)

    def test_wall_flat_before_first_corner(self):
        x = np.linspace(0.0, self.geom.x1, 10)
        y = self.geom.y_wall(x)
        assert np.allclose(y, 0.0)

    def test_wall_rises_between_corners(self):
        x = np.array([self.geom.x1, (self.geom.x1 + self.geom.x2) / 2, self.geom.x2])
        y = self.geom.y_wall(x)
        assert y[0] < y[1] < y[2]
        expected_y2 = (self.geom.x2 - self.geom.x1) * math.tan(math.radians(10.0))
        assert y[2] == pytest.approx(expected_y2, abs=1e-5)
        assert self.geom.y_corner2 == pytest.approx(expected_y2, abs=1e-5)

    def test_wall_flat_after_second_corner_when_theta2_zero(self):
        x = np.linspace(self.geom.x2, self.geom.L, 10)
        y = self.geom.y_wall(x)
        assert np.allclose(y, self.geom.y_corner2, atol=1e-5)

    def test_wall_normals_per_segment(self):
        # Flat segment (before x1): normal is (0, 1).
        nx, ny = self.geom.wall_normals(np.array([0.1]))
        assert nx[0] == pytest.approx(0.0, abs=1e-6)
        assert ny[0] == pytest.approx(1.0, abs=1e-6)

        # Compression incline (between x1 and x2): normal is
        # (-sin(theta1), cos(theta1)).
        nx, ny = self.geom.wall_normals(np.array([(self.geom.x1 + self.geom.x2) / 2]))
        assert nx[0] == pytest.approx(-math.sin(math.radians(10.0)), abs=1e-5)
        assert ny[0] == pytest.approx(math.cos(math.radians(10.0)), abs=1e-5)

        # Flat segment after x2 (theta2=0): normal is (0, 1) again.
        nx, ny = self.geom.wall_normals(np.array([self.geom.L - 0.1]))
        assert nx[0] == pytest.approx(0.0, abs=1e-6)
        assert ny[0] == pytest.approx(1.0, abs=1e-6)

    def test_interior_points_strictly_above_wall(self):
        pts = self.geom.sample_interior(500, seed=0)
        y_wall_at_x = self.geom.y_wall(pts[:, 0])
        assert np.all(pts[:, 1] > y_wall_at_x)
        assert np.all(pts[:, 0] >= 0.0) and np.all(pts[:, 0] <= self.geom.L)
        assert np.all(pts[:, 1] <= self.geom.H)

    def test_inlet_spans_full_height_at_x0(self):
        pts = self.geom.sample_inlet(20)
        assert np.allclose(pts[:, 0], 0.0)
        assert pts[:, 1].min() == pytest.approx(0.0, abs=1e-5)
        assert pts[:, 1].max() == pytest.approx(self.geom.H, abs=1e-5)

    def test_outlet_starts_above_wall_height_at_L(self):
        pts = self.geom.sample_outlet(20)
        assert np.allclose(pts[:, 0], self.geom.L)
        assert pts[:, 1].min() == pytest.approx(self.geom.y_corner2, abs=1e-5)
        assert pts[:, 1].max() == pytest.approx(self.geom.H, abs=1e-5)

    def test_upper_boundary_at_H(self):
        pts = self.geom.sample_upper(20)
        assert np.allclose(pts[:, 1], self.geom.H)

    def test_wall_segment_labels(self):
        seg = self.geom.wall_segment(np.array([0.1, 0.7, 1.3]))
        assert list(seg) == [0, 1, 2]

    def test_invalid_corner_ordering_raises(self):
        with pytest.raises(ValueError):
            CompressionExpansionRampGeometry(10.0, 0.0, x1=1.0, x2=0.4, L=1.6, H=0.8)
